artifact_location: file:///C:/Users/Juli/Desktop/Proyecto_Final_maestria/mlflow_geih/418150813951847250
creation_time: 1779946829393
experiment_id: '418150813951847250'
last_update_time: 1779946829393
lifecycle_stage: active
name: informalidad_geih_real
trace_location: null
workspace: default
