aliases: {}
creation_timestamp: 1779947122303
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1779948380558
name: informality_geih_champion
workspace: default
