artifact_uri: file:///C:/Users/Juli/Desktop/Proyecto_Final_maestria/mlflow_geih/418150813951847250/8ca7be46d59c442e91cbbea372ac81bd/artifacts
end_time: 1779946899457
entry_point_name: ''
experiment_id: '418150813951847250'
lifecycle_stage: active
run_id: 8ca7be46d59c442e91cbbea372ac81bd
run_name: RF_default
source_name: ''
source_type: 4
source_version: ''
start_time: 1779946899380
status: 3
tags: []
user_id: Juli
