artifact_uri: file:///C:/Users/Juli/Desktop/Proyecto_Final_maestria/mlflow_geih/418150813951847250/fb2aa84e65654fdabcc6cf1202358179/artifacts
end_time: 1779948132177
entry_point_name: ''
experiment_id: '418150813951847250'
lifecycle_stage: active
run_id: fb2aa84e65654fdabcc6cf1202358179
run_name: LR_baseline
source_name: ''
source_type: 4
source_version: ''
start_time: 1779948132062
status: 3
tags: []
user_id: Juli
